[window]
width = 450
height = 350
anchor = "center"
margin_top = 10
margin_bottom = 0
margin_left = 0
margin_right = 0
show_descriptions = true
show_paths = true
show_icons = true
show_search = true
show_actions = true
show_border = true
border_width = 2
use_gtk_colors = false
use_custom_css = true
max_entries = 50

[window.custom_navigate_keys]
up = "k"
down = "j"
delete_word = "h"

[theme.colors]
window_bg = "#0f0f0f"
search_bg = "#00000"
search_bg_focused = "#00000"
item_bg = "#0f0f0f"
item_bg_hover = "#181818"
item_bg_selected = "#1f1f1f"
search_text = "#e0e0e0"
search_caret = "#808080"
item_name = "#ffffff"
item_name_selected = "#4ECBFF"
item_description = "#a0a0a0"
item_description_selected = "#a0a0a0"
item_path = "#808080"
item_path_selected = "#808080"
border = "#4ECBFF"

[theme.corners]
window = 25
search = 25
list_item = 30

[theme.spacing]
search_margin = 15
search_padding = 15
item_margin = 4
item_padding = 4

[theme.typography]
search_font_size = 16
item_name_size = 14
item_description_size = 12
item_path_size = 12
item_path_font_family = "monospace"

[debug]
disable_auto_focus = true
enable_logging = true

[calculator]
enabled = true

[dmenu]
allow_invalid = false
case_sensitive = false

[web_search]
enabled = false
engine = "duckduckgo"
prefixes = []
